#!/bin/sh
echo "🔥 Pre-push hook is running..."
set -e

if [ ! -x "./buildEnv.sh" ]; then
    chmod +x ./buildEnv.sh
fi

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    bash ./buildEnv.sh
else
    ./buildEnv.sh
fi
