name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          check-latest: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '9.15.4'

      - name: Install dependencies
        run: |
          pnpm install
          # Если у вас есть pre-push хуки, делаем их исполняемыми
          [ -f .husky/pre-push ] && chmod +x .husky/pre-push

      - name: Build project
        run: pnpm build

      - name: Install Vercel globally
        run: pnpm add -g vercel@latest

      - name: Check Vercel version
        run: vercel --version

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --yes --token $VERCEL_TOKEN
